version: '3'

services:
  programmer.webserver:
    image: programmerwebserver
    ports:
      - "81:80"
    build:
      context: .
      dockerfile: Application/Programmer.WebServer/Dockerfile
    depends_on:
      - rabbitmq
      - calculator.webserver

  pnpservicefake:
    image: pnpservicefake
    ports:
      - "82:80"
    build:
      context: .
      dockerfile: Components/PnpServiceFake/Dockerfile
    depends_on:
      - programmer.webserver

  calculator.webserver:
    image: calculatorwebserver
    build:
      context: .
      dockerfile: Functional/Calculator.WebServer/Dockerfile
    ports:
      - "83:80"

  programmerwebui:
    image: programmer.webui
    build:
      context: .
      dockerfile: ../web-ui/programmer-webui/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - programmer.webserver

  rabbitmq:
    image: rabbitmq:3.7.3-management
    ports:
      - "15672:15672"
      - "5672:5672"